### ISSUE TITLE
SWO Exercise 5 missing

### ISSUE THREAD

**Issue by awenzelhuemer** [flohero/swo-exercise#1]
Dear Sir or Madam,

your Exercise 5 is missing from this repository.
Please upload so i can steal it!

Thank you.

Good night.

**Comment by fweingartshofer** [comment]
Done!

**Comment by awenzelhuemer** [comment]
Thanks mate!

**Comment by awenzelhuemer** [comment]
Next time earlier would be fine ;)

**Comment by fweingartshofer** [comment]
I'll try to upload it earlier ;)
